name: Test and coverage

on:
  push:
    branches:
      - master
  pull_request:

env:
  LANG: C.UTF-8

jobs:
  main:
    runs-on: ubuntu-latest
    container: ghcr.io/apertium/apertium-apy-cicd
    strategy:
      matrix:
        python-version:
          - 3.6.15
          - 3.7.12
          - 3.8.12
          - 3.9.9
          - 3.10.1
    env:
      PYENV_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Python installation
        uses: actions/cache@v2
        id: cache-python
        with:
          path: ${{ env.PYENV_ROOT }}/versions/${{ matrix.python-version }}
          key: ${{ runner.os }}-python${{ matrix.python-version }}-v1
      - name: Install Python
        run: pyenv install ${{ matrix.python-version }}
        if: steps.cache-python.outputs.cache-hit != 'true'

      - name: Install Pipenv
        run: pip install pipenv
      - name: Cache Pip dependencies
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python${{ matrix.python-version }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}-v1
      - name: Install Pip dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --dev

      - name: Build
        run: pipenv run make

      - name: Test
        run: NONPAIRS=/tmp/languages pipenv run make test

      - name: Coveralls
        run: pipenv run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
